name: Build & Test
on:
  workflow_dispatch:
    inputs: {}
  push:
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2-beta
        with:
          node-version: "12"
      - name: npm install
        uses: bahmutov/npm-install@v1
      - name: Build package
        run: npm run build
      - name: Test package
        run: npm t
