#
# Copyright (c) 2020 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
name: Test SDK

on:
  push:
    branches: [ main ]

jobs:

  build-next-imgs:
    runs-on: ubuntu-latest
    steps:
    - name: Install Operator SDK
      uses: shivanshs9/setup-k8s-operator-sdk@v1.1.3
      with:
        version: "^0.17.0"
